name: Pull Request Workflow

on:
  pull_request:
    branches:
      - master

env:
  NODE_ENV: test
  DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      # Step 1 - Checkout code
      - uses: actions/checkout@v3

      # Step 2 - Setting up Node.js environment
      - uses: ./.github/workflows/shared

      # Step 3 - Running prettier check
      - name: Run Prettier Check
        run: npm run prettier

      # Step 4 - Running linter
      - name: Run Linter
        run: npm run lint

      # Step 5 - Running tests
      - name: Run Tests
        run: npm test

      # Step 6: Running build (only if everything else succeeds)
      - name: Run Build
        run: npm run build
